# Generated by Django 5.1.2 on 2024-10-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='product_ids',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
