# Generated by Django 5.1.2 on 2024-10-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_link',
            field=models.URLField(default='https://example.com/default-image.jpg'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
